name: plant_it
description: "Open source gardening companion app ðŸª´"
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  dynamic_color: ^1.7.0
  intl: ^0.20.2
  flutter_lucide: ^1.6.2
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  json_serializable: ^6.9.5
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^19.4.0
  table_calendar: ^3.2.0
  http: ^1.3.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.0+1
  #workmanager: ^0.9.0+2
  # https://github.com/fluttercommunity/flutter_workmanager/issues/594
  # https://github.com/fluttercommunity/flutter_workmanager/issues/588
  workmanager:
    git:
      url: https://github.com/aldisa546/flutter_workmanager.git
      ref: upgrade/flutter-3.29
  palette_generator: ^0.3.3+6
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  command_it: ^8.0.0
  result_dart: ^2.1.1
  logging: ^1.3.0
  flutter_localization: ^0.3.3
  provider: ^6.1.5
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  material_shapes: ^0.0.2
  shared_preferences: ^2.5.3
  flutter_carousel_widget: ^3.1.0
  # https://pub.dev/packages/flutter_popup
  # https://pub.dev/packages/dotted_border
  # https://pub.dev/packages/chip_list
  # https://pub.dev/packages/advanced_chips_input
  # https://pub.dev/packages/introduction_screen
  # https://pub.dev/packages/system_theme
  # https://pub.dev/packages/sliver_tools
  # https://pub.dev/packages/quick_actions
  # https://pub.dev/packages/image_picker
  # https://pub.dev/packages/notification_listener_service
  # https://pub.dev/packages/home_widget
  # https://pub.dev/packages/expandable_page_view


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.10.1
  mockito: ^5.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/generic-plant.jpg
  generate: true
