blank_issues_enabled: false
contact_links:
  # - name: ğŸ› Bug report
  #   url: https://github.com/MDeLuise/plant-it/issues/new?assignees=&labels=&projects=&template=bug_report.yml
  #   about: Report a bug in Plant-it.
  - name: ğŸ’¬ Question and Help
    url: https://github.com/MDeLuise/plant-it/discussions/new?category=q-a
    about: Ask and answer questions abount Plant-it.
  - name: ğŸš€ Feature Request
    url: https://github.com/MDeLuise/plant-it/discussions/new?category=feature-request
    about: Request a feature or enhancement in Plant-it.