apiVersion: v1
kind: ConfigMap
metadata:
  name: plantitconfig
data:
  MYSQL_HOST: "db-service"
  MYSQL_PORT: "3306"
  MYSQL_USERNAME: "root"
  MYSQL_DATABASE: "bootdb"
  JWT_EXP: "1"
  USERS_LIMIT: "-1"
  UPLOAD_DIR: "/upload-dir"
  API_PORT: "8080"
  LOG_LEVEL: "DEBUG"
  ALLOWED_ORIGINS: "*"
  CACHE_TTL: "86400"
  CACHE_HOST: "cache-service"
  CACHE_PORT: "6379"
  SSL_ENABLED: "false"
  CERTIFICATE_PATH: "/"
