baseURL = '/'
languageCode = 'en-us'
title = 'Plant-it docs'
theme = "hugo-theme-learn"

[params]
    editURL = "https://github.com/MDeLuise/plant-it/tree/main/online-resources/documentation/content/"
    author = "Massimiliano De Luise"
    description = "Documentation site about the app Plant-it"
    showVisitedLinks = true
    disableSearch = false
    disableAssetsBusting = false
    disableInlineCopyToClipBoard = false
    disableShortcutsTitle = false
    disableLandingPageButton = false
    disableLanguageSwitchingButton = false
    disableBreadcrumb = false
    disableMermaid = false
    customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
    disableNextPrev = false
    ordersectionsby = "weight"
    themeVariant = "green"
    #custom_css = ["css/foo.css", "css/bar.css"]
    titleSeparator = "-"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
    name = "<i class='fab fa-github'></i> Github repo"
    identifier = "ds"
    url = "https://github.com/MDeLuise/plant-it/"
    weight = 10
[[menu.shortcuts]] 
    name = "<i class='fas fa-camera'></i> Screenshots"
    url = "/screenshots"
    weight = 11
