name: Measure coverage

on:
  pull_request:
    branches:
    - main

jobs:
  calculate_coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 20

      - name: Run backend tests
        run: mvn clean install
        working-directory: ./backend

      - name: Run Coverage
        run: mvn jacoco:report
        working-directory: ./backend

      - name: JaCoCo Report to PR
        uses: Madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: ğŸ“ Coverage Report For Server Service
          pass-emoji: ğŸŸ¢
          fail-emoji: ğŸ”´

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
